### ISSUE TITLE
dummyCtx.close is not a function

### ISSUE THREAD

**Issue by karensg** [nehz/ngWebAudio#10]
Hi,

In Safari 7 and 8 I get an error that dummyCtx.close on line 30 is not a funciton

I solved it so far like this:

``` javascript
if(angular.isFunction(dummyCtx.close)) {
   dummyCtx.close();
}
```

But you might have more idea what is actually going on. I have an idea that this will break the creation of new AudioContext constructions.

**Comment by nehz** [comment]
Thanks. Some older browser apprently don't have AudioContext.close(). d8036de4738ba9e5968bda9143f72ca26699425e should fix it.
