### ISSUE TITLE
NotSupportedError: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).

### ISSUE THREAD

**Issue by karensg** [nehz/ngWebAudio#11]
Sorry for bothering you with lots of issues: I am testing with lots of users, so this will be a perfect way to get all the bugs out of the library. I hope you don't mind.

I get the following error on Chrome 48 on Windows 10. I guess the library should only use one AudioContext on the page, right?

```
NotSupportedError: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).
```

**Comment by nehz** [comment]
That's weird, should only use 1 AudioContext for the module. 
Same error on other browsers?
Also are you using requireJS/browsify (should work with them, but curious) ?

**Comment by karensg** [comment]
No, I am not using requireJS/browsify. I do use all kind of minifications and uglifications. But I did not have any problems with that so far.
I am tracking all kind of errors which my users encounter. So far it happened only with 2 users, both using Windows 10 and Chrome.

I will try to reproduce it myself when I get to a Windows 10 machine but I assume this should happen when a user plays more than 6 songs.
