### ISSUE TITLE
TypeError: Object #<AudioContext> has no method 'createGain'

### ISSUE THREAD

**Issue by karensg** [nehz/ngWebAudio#13]
Hi,

On Android 4.3 I get the following error:
`TypeError: Object #<AudioContext> has no method 'createGain'`

Any ideas?

Karens

**Comment by nehz** [comment]
According to MDN, createGain requires webkit prefix for older browsers (e.g `webkitCreateGain`) however latest Chrome has already removed it so I can't test it yet. Can you check if `webkitCreateGain` exists? 

EDIT: on second note, Android stock browser might not support this yet (? on MDN)

**Comment by karensg** [comment]
I only have the ability to test on 4.4 through [BrowserStack](https://www.browserstack.com)
createGain is available there.

**Comment by nehz** [comment]
I've pushed an update which will bypass the gain node if `createGain()` is not available.
Let me know how it goes. (Probably also slack off on the test case for this one. Will be a bit hairy to produce a non-flaky test case)

**Comment by karensg** [comment]
Nice. Thanks for the super fast response. I added the code. Let's see and wait if the error returns.

**Comment by karensg** [comment]
The error did not come back any more. Thanks
