### ISSUE TITLE
SyntaxError: audio resources unavailable for AudioContext construction

### ISSUE THREAD

**Issue by karensg** [nehz/ngWebAudio#14]
On iOs 8.3 I also get the following error:
`SyntaxError: audio resources unavailable for AudioContext construction`

My code is minified, here is the problem:
`{snip} sFunction(h.close)&&h.close(),ngWebAudio.audioContext=new g}var k=ngWebAudio.audioContext}var l={},m={},n=function o(a,b){snip}`

Any ideas on this one?

**Comment by nehz** [comment]
This is probably related/same as #11. The module should be caching the audio context to reuse; is it possible to create a minimal test case that can reproduce this ?

**Comment by karensg** [comment]
True, it is probably related. I can't reproduce it either. I just see in my logs that this happens more often for the Apple devices.
Can it be that somehow the factory gets destroyed and recreated, while AudioContext is created again. Is there maybe a browser method to get the current AudioContext?

**Comment by nehz** [comment]
Angular factories don't get destroyed if I remember correctly, it is created once during app init/bootstrap. It might be possible that multiple independent full angular apps are getting bootstrapped inside the same html document ? Alternatively it could be as the error message suggest; that there actually isn't enough resources (RAM?) or something is holding the audio hardware ?. Again it is hard to say without being able to reproduce it :(

There is no AudioContext unless you explicitly request to create one. And I don't believe there is a way to get currently created AudioContexts or at least I can't find anything on MDN

**Comment by karensg** [comment]
Hi @nehz,

I finally found the cause of this problem. When a user opens more than 6 tabs where ngWebAudio is loaded, the page crashes because there are no resources any more. I solve it now by injecting the webAudio service only when the song has actually to be played. 
Not sure if this can somehow be solved in the library itself. Maybe save the reference to the object in the local storage? Then a song in tab A will be stopped before another song in tab B starts.
Same issue in #11 of course.

Greetings,
Karens
