### ISSUE TITLE
Origin 'null' is therefore not allowed access.

### ISSUE THREAD

**Issue by mtalhajamil** [nehz/ngWebAudio#3]
I can download file from a website & it also runs via ng-audio. But when I run it with Web Audio it gives me
`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

Server is not mine. So where is the difference & what is the solution?

**Comment by nehz** [comment]
Is this on a local machine ? Origin 'null' should be the local file system. Chrome has a setting/flag that will allow this (--allow-file-access-from-files). Else you will need some sort of dev server to host the file (can be localhost)

**Comment by mtalhajamil** [comment]
I am using nws as dev server. Everyone will not disable setting from chrome. I am building a clients side ionic application. just to give you an idea: http://quranmedia.herokuapp.com/#/ayatView

ng-audio is a wrapper over audio tag of html 5 so it works but this module is sending XHR requests
![screen shot 2016-01-28 at 4 27 10 pm](https://cloud.githubusercontent.com/assets/9127273/12643132/0e9e0c86-c5dc-11e5-86c9-2577ee899957.png)

**Comment by nehz** [comment]
You will need to setup the correct CORS for the server serving the audio files (as with any XHR request) if you are doing cross domain requests. For example if your site is hosted on http://abc.com but your audio files are on http://xyz.com. If both the site and the files are on same domain this is not necessary.

See http://stackoverflow.com/questions/10143093/origin-is-not-allowed-by-access-control-allow-origin
or google CORS

**Comment by nehz** [comment]
Oh you don't own the server. The only way is for your server (that hosts your site) to fetch the audio files on the backend and serve them on the same domain. If your don't own the media or server, there might be legal and/or ethical ramifications by doing this, so it is best to contact the administrator of the other site before you do this.

**Comment by mtalhajamil** [comment]
Thank you for your help. I helped me a lot.
