### ISSUE TITLE
Audio object does not set stopped property when track is over

### ISSUE THREAD

**Issue by karensg** [nehz/ngWebAudio#9]
Hi,

I just realized that the Audio object does not set `stopped` property automatically when the track is over.
Somehow, if then, I open the Chrome console, the `stopped` property changes to `true`

Karens

**Comment by nehz** [comment]
Possible for some sample code to show this behaviour ?

**Comment by karensg** [comment]
Sure, this is the code. This function is triggered with ng-click from HTML.

``` javascript
$scope.playSong = function(i) {
    var url = $scope.artist.songs[i].spotifyUrl;
    if (angular.isDefined($scope.currentSong) && $scope.currentSong.src === url) {
      if (!$scope.currentSong.stopped) {
        $scope.currentSong.pause();
      } else {
        $scope.currentSong.play();
      }
    } else if (angular.isUndefined($scope.currentSong) || $scope.currentSong.id !== url) {
      if (angular.isDefined($scope.currentSong)) {
        $scope.currentSong.stop();
      }
      $scope.currentSong = new WebAudio(url);
      $scope.currentSong.play();
    }
};
```

**Comment by nehz** [comment]
Are you observing the `stopped` attribute in a view binding e.g `{{ currentSong.stopped }}` ?
I might add a rootScope `$apply` to callbacks regardless though...

**Comment by karensg** [comment]
Yes, I am watching the variable but it does not change. However, it changes when I just pause.

**Comment by nehz** [comment]
Pushed an update 89dc7ae26a3386d70169cffe63bbe6fa1851d50b. Hopefully this should allow you to observe `audio.stopped` in views.

**Comment by karensg** [comment]
It works now indeed. Thanks
